### PR TITLE
WebLoader: Added absoluteUri option

### PR DESCRIPTION
**Pull request by juniwalk**
I implemented this a while ago because I thought I needed it, reality was different and I was left with this.

I am sending this PR in case you would like to merge it.

### CODE REVIEW

**Comment by juniwalk** [comment]
ping @janmarek @fprochazka 
Guys could you check it out and merge / close it?:)

**Comment by fprochazka** [comment]
@juniwalk well, the code looks OK, although I'd preffer a testcase for it.

But I must ask... what is the point of having the url absolute? I would understand if you had another static domain on your http server, to get rid of cookies in asset requests, but just adding the url as absolute servers no purpose imho. Can you please explain why this is needed?

**Comment by juniwalk** [comment]
@fprochazka Hey, like I said in first message, I implemented this because I had some weird error going on and I thought this would fix it, it did but it was not necessary.

Since I already got the code I thought I'd send PR so you could say if it is usable or not, there is no need to merge it, I just wanted to be sure you have no use for it before I delete it. :)

**Comment by fprochazka** [comment]
@juniwalk I don't think merging code just because it was written is a good reason :)

**Comment by juniwalk** [comment]
@fprochazka I know, I just did not know if it would be useful to anyone so I tried. :)

**Comment by fprochazka** [comment]
@juniwalk thanks anyway!

**Pull request closed without merging**
