### PR TITLE
+ Added SVG CSS3 icon

### PR DESCRIPTION
**Pull request by bckp**
I added CSS3 icon instead of globe, becouse Tracy now uses SVG and it looks better

### CODE REVIEW

**Comment by janmarek** [comment]
You probably forgot to delete the old icon file.

**Comment by fprochazka** [comment]
@bckp great! Thank you!

**Comment by bckp** [comment]
@janmarek True, will fix it ASAP :)

**Comment by fprochazka** [comment]
@bckp sorry, the icon was so nice I had to fix it right away :D

**Comment by fprochazka** [comment]
Merged https://github.com/janmarek/WebLoader/commit/4a7ac5864442e0d26ef3aac4da45e7e03a35c9e2

**Comment by fprochazka** [comment]
Looks like this

snimek obrazovky porizeny 2015-09-08 15 54 56

**Comment by bckp** [comment]
:-D

**Pull request closed without merging**
