### PR TITLE
added CssShrinkFilter

### PR DESCRIPTION
**Pull request by bckp**
Added CssShrinkFilter, this is small method, that minifies CSS, strip
comments etc...

### CODE REVIEW

**Comment by fprochazka** [comment]
I like the idea. But I cannot merge this without tests. And also, I would preffer using an optional library and writing only filter class with integration of that library.

**Comment by bckp** [comment]
@fprochazka 

Ad test,
Test should not be problem, I can write some

Ad library
This is so simple code, I belive it can be part of WebLoader, maybe not Filter, but let's say some kind of extension?

**Comment by fprochazka** [comment]
Btw, you write styles in plain old CSS? Or why do you need to minify it? Can't less filters minify it by themselfs?

**Comment by bckp** [comment]
I wrote in Less, but some plugins are in plain CSS.
You can reject this PR, we can add some kind of note, if people will want it, I just want to share code, that may be usefull for someone

**Comment by fprochazka** [comment]
I agree that some kind of shrink should be included here :)

**Comment by fprochazka** [comment]
The `joseki/webloader-filters` is now suggested https://github.com/janmarek/WebLoader/commit/029fa701e54dabb13778ee33e3762697c60d18f5. It provides [CSSMin filter](https://github.com/Joseki/WebloaderFilters/blob/cd40428a62a4057a066791c9c59f7c75c345398c/src/Joseki/Webloader/CssMinFilter.php) via 3rd party lib. So I guess this can be closed. Thank you for your work!

**Pull request closed without merging**
